    version: '3'

    services:
      #lance un serveur web apache
      web:
        build: docker/apache2
        ports:
          - 8080:80
        volumes:
          - .:/usr/local/apache2/htdocs
      #Lance un serveur php-fpm qui sera lié sur apache
      php:
#        Pour utiliser php 7.2-fpm + pdo
        build: docker/php
        #Récupère les volumes définis sur web
        volumes:
          - .:/usr/local/apache2/htdocs
      #Lance un serveur mysql
      db:
        image: mysql:5.7
        #permet de conserver les bases de données
        volumes:
          - ./.mysql:/var/lib/mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      pma:
        image: phpmyadmin/phpmyadmin
        ports:
          - 8081:80
        links:
        #On lie DB à PhpMyAdmin
          - db:db